### ISSUE TITLE
大写O也太像0了

### ISSUE THREAD

**Issue by kidzgy** [aleigood/Hybrid-Font#1]
![微信截图_20220105161649](https://user-images.githubusercontent.com/6967810/148183708-456fed8a-0e45-4f63-95eb-8281944dcd20.png)

![微信截图_20220105162048](https://user-images.githubusercontent.com/6967810/148184193-bb748469-6a4c-4c14-ae01-aa573292700e.png)
如图，如果大写O与数字连在一起的话，第一时间不会认为是O，而是0

**Comment by kidzgy** [comment]
可能是一开始还没习惯哈哈，我发现用回Source Code Pro也会有同样的感觉

**Comment by aleigood** [comment]
所以编程用字体零的中间都会有点或横线作区分，习惯就行
