### ISSUE TITLE
错误的空白占位字符

### ISSUE THREAD

**Issue by third0light** [aleigood/Hybrid-Font#2]
![2](https://user-images.githubusercontent.com/26151916/203723671-dfa638ba-ed63-4c57-ab9e-5be1580b4802.png)

![1](https://user-images.githubusercontent.com/26151916/203723650-84d64f48-4af2-45ae-b5c5-119d9746a601.png)

被选中的半角空格字符的圆点错误地非常靠右。在使用其他字体是没有这个情况。

**Comment by aleigood** [comment]
圆点是编辑器根据字体宽度渲染的，字体本身不包含这个字符
